# Site settings
title: Be More Woman on Rails
logo: womanonrails.jpg
email: please-do-not-spam-me@womanonrails.com
description: Każda chwila naszego życia jest niezwykle cenna. To nasz skarb. Nie warto go marnować na smutek, frustracje czy stres. Zapraszam Cię serdecznie na Be More. Przyłącz się do mnie i zacznij tworzyć swoje wymarzone życie. Życie pełne radości, zrosumienia i szczerości.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bemore.womanonrails.com" # the base hostname & protocol for your site
twitter_username: womanonrails
github_username:  womanonrails
author: Agnieszka Małaszkiewicz
disqus_shortname: be-more
lang: pl
tech_blog:
  title: Świat programowania widziany oczami kobiety - mój drugi blog
  name: Woman on Rails
  url: https://womanonrails.com/pl

meta:
  title: Be More - jak być lepszym, szczęśliwym człowiekiem
  description: Chcesz być szczęśliwy? Szczęśliwy na własnych warunkach? Tu znajdziesz moje przemyślenia na temat życia.

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false
    line_numbers: false

pagination:
  debug: false
  enabled: true
  per_page: 12
  permalink: '/page:num/'
  title: ':title - strona :num'

# Plugins settings
plugins:
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - README.md
