# Site settings
title: Be More Woman on Rails
logo: womanonrails.jpg
email: please-do-not-spam-me@womanonrails.com
description: Każda chwila naszego życia jest niezwykle cenna. To nasz skarb. Nie warto go marnować na smutek, frustracje czy stres. Zapraszam Cię serdecznie na Be More. Przyłącz się do mnie i zacznij tworzyć swoje wymarzone życie. Życie pełne radości, zrosumienia i szczerości.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bemore.womanonrails.com" # the base hostname & protocol for your site
twitter_username: womanonrails
github_username:  womanonrails
author: Agnieszka Matysek
disqus_shortname: be-more

meta:
  title: Be More - jak być lepszym, szczęśliwym człowiekiem
  description: Chcesz być szczęśliwy? Szczęśliwy na własnych warunkach? Tu znajdziesz moje przemyślenia na temat życia.

# Build settings
markdown: redcarpet
paginate: 12

gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - gh-pages.sh
  - README.md
